# Generated by Django 3.2.3 on 2021-05-18 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0002_dateforappointment_month'),
    ]

    operations = [
        migrations.AddField(
            model_name='dateforappointment',
            name='is_showed',
            field=models.BooleanField(blank=True, default=True, verbose_name='Дата показывается для выбора'),
        ),
    ]
