# Generated by Django 3.2.3 on 2021-05-20 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0003_dateforappointment_is_showed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='is_booked',
            field=models.BooleanField(default=False, verbose_name='Забронировано'),
        ),
    ]
