# Generated by Django 3.2.3 on 2021-05-20 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0004_alter_appointment_is_booked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='date_appointment',
            field=models.DateField(verbose_name='Дата записи'),
        ),
    ]
