# Generated by Django 3.2.3 on 2021-05-20 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0005_alter_appointment_date_appointment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='date_of_write',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Дата записи'),
        ),
    ]
