# Generated by Django 3.2.3 on 2021-05-20 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0006_alter_appointment_date_of_write'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DateForAppointment',
        ),
    ]
